# Generated by Django 5.0.4 on 2024-04-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_userprofile_height_userprofile_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
