# Generated by Django 5.0.1 on 2024-04-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vlog_title", models.CharField(max_length=400)),
                ("vlog_descrription", models.TextField()),
                ("vlog_image", models.ImageField(upload_to="vlog/images")),
                ("vlog_post_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
