# Generated by Django 5.0.1 on 2024-04-23 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donationcenters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bloodrequest",
            name="is_fulfilled",
        ),
        migrations.RemoveField(
            model_name="bloodrequest",
            name="location",
        ),
        migrations.RemoveField(
            model_name="bloodrequest",
            name="needed_by",
        ),
        migrations.RemoveField(
            model_name="bloodrequest",
            name="reason",
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="blood_quantity",
            field=models.CharField(
                choices=[
                    ("1 Bag", "1 Bag"),
                    ("2 Bags", "2 Bags"),
                    ("3 Bags", "3 Bags"),
                    ("4 Bags", "4 Bags"),
                    ("5 Bags", "5 Bags"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="donation_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="hemoglobin_level",
            field=models.CharField(
                choices=[
                    ("1", 1),
                    ("2", 2),
                    ("3", 3),
                    ("4", 4),
                    ("5", 5),
                    ("6", 6),
                    ("7", 7),
                    ("8", 8),
                    ("9", 9),
                    ("10", 10),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="where_need",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="bloodrequest",
            name="why_need",
            field=models.CharField(
                choices=[
                    (
                        "Oxygen Delivery",
                        "To supply oxygen to injured tissues and organs to prevent cell death.",
                    ),
                    (
                        "Clotting",
                        "To stop excessive bleeding and prevent further blood loss.",
                    ),
                    (
                        "Nutrient Transport",
                        "To provide essential nutrients for tissue repair and healing.",
                    ),
                    (
                        "Waste Removal",
                        "To clear away metabolic waste products from damaged tissues.",
                    ),
                    (
                        "Immune Response",
                        "To transport immune cells to the site of injury to prevent infections and promote healing.",
                    ),
                    (
                        "Maintaining Blood Pressure",
                        "To ensure adequate circulation and perfusion to vital organs.",
                    ),
                    (
                        "Temperature Regulation",
                        "To help regulate body temperature at the site of injury.",
                    ),
                    (
                        "Maintaining pH Balance",
                        "To regulate the body's acid-base balance, which is crucial for cellular function.",
                    ),
                    (
                        "Preventing Shock",
                        "Adequate blood volume is necessary to prevent shock, a life-threatening condition that can occur due to severe blood loss.",
                    ),
                    (
                        "Supporting Organ Function",
                        "To provide the necessary components for the proper functioning of organs and tissues affected by the accident.",
                    ),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
