# Generated by Django 5.0.1 on 2024-04-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donationcenters", "0003_bloodrequest_additional_information_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodrequest",
            name="is_donate",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="why_need",
            field=models.CharField(
                choices=[
                    ("Oxygen Delivery", "Oxygen Delivery"),
                    ("Clotting", "Clotting"),
                    ("Nutrient Transport", "Nutrient Transport"),
                    ("Waste Removal", "Waste Removal"),
                    ("Immune Response", "Immune Response"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
