# Generated by Django 5.0.1 on 2024-04-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donationcenters", "0004_bloodrequest_is_donate_alter_bloodrequest_why_need"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="is_donate",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
