# Generated by Django 5.0.1 on 2024-04-23 23:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("donationcenters", "0006_rename_is_donate_bloodrequest_is_donated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bloodrequest",
            old_name="is_donated",
            new_name="is_donate",
        ),
    ]
